### ISSUE TITLE
undefined acronyms are confusing to new users

### ISSUE THREAD

**Issue by 33thou** [ros2/ros_core_documentation#19]
I'm working my way through the official tutorials, and am currently on creating [custom ROS interfaces](https://index.ros.org/doc/ros2/Tutorials/Custom-ROS2-Interfaces/). It describes `find_package(rosidl_default_generators REQUIRED)` which I googled, leading here, but the terms are not well defined. I assume "IDL" stands for "interface definition language", but it's not at all clear.

I've noticed that ROS code has a tendency toward abbreviation which can be confusing. Another example: does "cli" mean "client" or "command line interface"?

Recommend defining acronyms as often as possible, and avoiding them entirely when possible

**Comment by jacobperron** [comment]
@33thou Thanks opening a issue! You are correct that IDL stands for "interface definition language" and CLI is "command line interface". If you have some changes you'd like to propose related to clarifying acronyms in this repository or https://github.com/ros2/ros2_documentation (where the tutorials live), pull requests are welcome!

**Comment by 33thou** [comment]
thanks - didn't realize this repo was ros and not ros2

**Comment by jacobperron** [comment]
> didn't realize this repo was ros and not ros2

This repository is for ROS 2. It's a bit confusing since our documentation is currently scattered across multiple repositories, but we're in progress of improving and consolidating documentation.
